### ISSUE TITLE
Create the core react components

### ISSUE THREAD

**Issue by Angelmmiguel** [bitnami/hex#219]
Core components must be added to the project. 

* [x] Grid #234
* [x] Row #237
* [x] Column #238  
* [x] Anchor #247
* [x] Box #229 
* [x] Text #229 
* [x] Heading #243
* [x] Code #240 
* [x] Blockquote #242
* [x] Separator #241 

# Exposing helpers (spacing, typography...)

I'm working on the HEx-react package (core components). I was thinking how to manage all the common helpers that we can apply to the different components (margins, paddings, text colors...). My first approach has been to create "wrapper" components that includes this kind of helpers as `props`, so you don't need to deal with the `classNames`. For example:

```
import { H1 } from '@bitnami/hex-react';
<H1 marginTop="big">Test!</H1>
```
However, it means you need to import all the H*, P, UL... It can be tedious to think of using the wrapper components all the time you want to use any helper.

Another option could be to use the `Box` component. It's a generic one that includes all the helpers. Currently, it uses a `div` but I can make it customizable. The counterpart of this solution is that you need to add a second component in case you want to use these helpers:

```
import { Box } from '@bitnami/hex-react';
<Box marginTop="big">
 <h1>Test!</h1>
</Box>
```

The last option is to ignore all these components and encourage developers to use the `classNames` all the time. But I feel this is not React friendly and it's more verbose than just using the props.

```
<h1 className="marginTop">Test</h1>
```

**What do you think or you expect the HEx-react package will provide you?** Thanks! :smile:

PS: I've already started with the first approach, but the PRs are not landed yet:

- #229
- #230

**Comment by andresmgot** [comment]
I would go with option 1 as well: it has the downside that regular HTML tags are not going to be used anymore but it has the benefit that properties would be now discoverable. I am okay as well with option 3 though: it's just a bit more difficult to search for the correct property in https://design.bitnami.com

**Comment by prydonius** [comment]
hmm option 1 is a bit strange to me, do any other frameworks do something like this?

**Comment by Angelmmiguel** [comment]
@prydonius it depends on the framework. However, they don't usually create wrapper components to replace every HTML tag. For example, https://rebassjs.org/ defines more generic components like `Title`. Although they also define some specific ones like `Link`.

Others frameworks allows you to customize the inner element in the component or replace the HTML tags directly. This is how Shopify/polaris works. You can see their [`Heading` component](https://polaris.shopify.com/components/titles-and-text/heading#navigation) that receives the heading level or the [`List` one](https://polaris.shopify.com/components/lists-and-tables/list#navigation), that redefines the ul/li tags.

**Comment by earnubs** [comment]
There's a lot of issues to unpack here :)

Speaking from an app developers point of view...

Wrapping every HTML element isn't practical, nor is it neccessary imo. `div` and `span` for example are simply (from a certain point of view) shorthand for block and inline elements, there's no general styling, semantic or behavioural complexity we need to wrap into a module. 

There may be specific use cases of a div that we do want to wrap into a component because they do involve complexity: for example a call-out comes with style, background, border-radius and treatment of content that makes wrapping into a component worthwhile.

With headings it's a variation of the same idea, I'd want to keep the HTML elements h1-6 as simple as possible, so they can be easily used without having to override CSS. A React `H` (for example) component can encapsulate the main header styles/behaviours of your app:

```
<H style="massive" rank="1">
  Man Walks on Moon!
</H>
// output => <h1 class="hex-heading--massive">Man Walks on Moon!</h2>
```

Same for ul/li, only wrap up specific implementation of a list (eg Table of Contents), not the element itself, because it's too simple.

`Form` elements are generally not too simple, have specific style and behaviour, and we benefit from wrapping those into React components for the typical use cases. (I would still keep the bare elements as plainly styled as possible.)


On helpers, I would probably shy away from widespread use of helpers to augment CSS classes. What you want is a library that contains self contained components that are fully encapsulated, and build up by composing smaller/simpler components.

So, following a component based methodolgy, this:
`<h1 className="marginTop">Test</h1>`

would become this:

`<h1 className="Heading--rank-1">Test</h1>`

With the CSS entirely defined with the component in `Heading.css`:

```
/components/Heading
  /components/Heading/index.js
  /components/Heading/Heading.css
  /components/Heading/Heading.test.js
```

This is where we diverge from the CSS library model into a pure component model, we don't generally apply CSS classnames that represent a general style augmentation.

Sorry, I have to run, will probably read this tomorrow and see mistakes!

**Comment by prydonius** [comment]
I prefer the approach Spotify have, and it actually sounds similar to what @earnubs is suggesting with the `H` example. It might be a good idea to put together a design doc on what components it makes sense to make and what configuration options they should have, as it's not immediately clear to me what we'd want to make components and what things should just use regular HTML tags.

**Comment by Angelmmiguel** [comment]
> Speaking from an app developers point of view...
>
> Wrapping every HTML element isn't practical, nor is it neccessary imo. div and span for example are simply (from a certain point of view) shorthand for block and inline elements, there's no general styling, semantic or behavioural complexity we need to wrap into a module.
>
> There may be specific use cases of a div that we do want to wrap into a component because they do involve complexity: for example a call-out comes with style, background, border-radius and treatment of content that makes wrapping into a component worthwhile.
> 
> With headings it's a variation of the same idea, I'd want to keep the HTML elements h1-6 as simple as possible, so they can be easily used without having to override CSS. A React H (for example) component can encapsulate the main header styles/behaviours of your app:

+1 to this @earnubs. At the beginning I thought it was a good idea to have the helpers in all the components, but it makes much more sense to focus on actual components rather than independent tags. 

I'm gonna create a `Box` component which includes all the helpers. We can use it in case we want to wrap any HTML tag in a container with some styling (spacing, background, etc).

For the other HTML tags, I'm gonna create some logic components that encapsulates more logic and expose only the props that makes sense for it.

> With the CSS entirely defined with the component in Heading.css:
>
> /components/Heading
>  /components/Heading/index.js
>  /components/Heading/Heading.css
>  /components/Heading/Heading.test.js
> This is where we diverge from the CSS library model into a pure component model, we don't generally apply CSS classnames that represent a general style augmentation.

As you mention, this makes sense for pure components but here we're contributing to a hybrid library. We need to maintain compatibility with the current approach, so the CSS code must be kept in a separate package. I want to refactor a bit the CSS part, but that's something that will come later.

However, the components section of the CSS library defines real components like [`Terminal`](https://design.bitnami.com/category/Components/Code/). So, I believe it fits with our desired implementation of the React components.

For the CSS helpers like `margin-t-big`, we can kept them in the `Box` component. 

>  I prefer the approach Spotify have, and it actually sounds similar to what @earnubs is suggesting with the H example. It might be a good idea to put together a design doc on what components it makes sense to make and what configuration options they should have, as it's not immediately clear to me what we'd want to make components and what things should just use regular HTML tags.

For now, I'm gonna move the Core components. This is the list I plan to finish for this iteration:

* Grid
* Row
* Col
* Link
* Box
* Heading (or H)
* CodeBlock (with copy-to-clipboard feature!)
* Blockquote
* Separator

What do you think @earnubs @prydonius?

**Comment by earnubs** [comment]
We talked about this in the Frontend Sync meeting today and I'll try to summarise, the summary may wander a bit though, and @angel or @lvalverde may remember things differently so don't take this as set in stone. :)

We want to deliver a tool (or tools) that enables delivery of Bitnami's various outputs in line with the Bitnami brand in as efficient a manner as possible. For this we have HEx, the Bitnami design system.

What is a design system? 
> A design system is a collection of reusable components, guided by clear standards, that can be assembled together to build any number of applications.
https://www.invisionapp.com/blog/guide-to-design-systems/

HEx must meet the needs of broadly 2 implementations, document based design and application based design. These have what may be subtle but are certainly significant differences in terms of the demands they place on HEx.

# Document Based Design

Deals with largely uniform concepts: headers, sections, tables, images.
Is a good fit for breadth-wise change, where updating an common ancestor (eg. font-size) of the design system propagates as a change across implementations in a safe and efficient manner.

# Application Based Design

Deals with highly specialised concepts: aka. widgets.
Is a poor fit for breadth-wise change, changes which propagate across components tend to break the component in obvious and non-obvious ways, leading to costly and unmanageable refactoring epics.

Companies have come unstuck on having to evolve an application design to keep up with a competitor because the cost of refactoring exceeded their developer budget.

A way to address this issue is to encapsulate components style and behaviour, to compose rather than inherit. This is the recommended pattern of development for React based applications and addresses the refactoring cost by moving refactoring to being breadth-wise to depth-wise. Refactoring is now taken in a component by component, and is more manageable for smaller teams.

# How do we "encapsulate" CSS?

There are two popular methodolgies: BEM and SUIT, for our purposes they're the same idea, we're going to talk about SUIT ... this is going to become a very long comment if I explain SUIT or BEM so I'll just leave a link here https://suitcss.github.io/

SUIT would actually give us 2 things:

1. CSS with limited scope (a very good thing in app development)
2. And with a prefix, clear developer hint as to what library a class name belongs to and where to find it: `hex-Header` is a HEx class and I'd look for the implementation in `src/components/Header` (one of the rules of SUIT, if enabled in a linter, is the component name must match the file name).

# OK Great! SUIT All The Things!

Yes, but ...

HEx deals with apps and /documents/, and SUIT / componentised CSS isn't actually the best solution for documents.

So, we have to discuss if we want to adopt componentised CSS at all, or restart HEx entirely for React, or a mixture of both models.

# Conclusion

In an ideal world I'd probably have HEx give us 2 (or more) outputs, one a document style sheet to cover the use cases of Marketing and static sites across Bitnami, the second a highly encapsulated component system (in our case, at least initially, React Component modules) with a focus on application design (I believe that even the approach to graphically designing the basic elements is different between the 2 models).

However, we don't have the resources to do that right now and some mixing of the 2 models is pragmatic.

## Stacksmith is currently a mixture of both models

The current development model for Stacksmith was arrived at less by design and more by neccessity, but it's roughly this (modulo some trial and error on my part in the code base): 

- We have a base CSS stylesheet, from HEx, everything is neccessarily layered on this CSS as it is global and affects bare HTML elements, this is not pure component based delivery.
- Where we see common components that could be reused outside Stacksmith in HEx we build them with a  dependency on HEx (either implicit in that they depend on some global CSS, or explicit in that they import color.scss or some HEx deliverable) but with any additions we make they are componentised (eg. https://github.com/bitnami/stacksmith/blob/master/frontend/src/components/hex/Button/Button.scss). This component CSS has a `hex-` prefix for class names.
- Where our component is unique, we isolate it from HEx and make the CSS conform to SUIT (eg. https://github.com/bitnami/stacksmith/blob/projects-page-title/frontend/src/components/Header/ProjectHeader.css). This CSS has a `sm-` prefix for class names.

We have some protection from unmangeable refactors and we have clarity on where CSS comes from, but we also leverage the existing work in HEx for the more "document" centric parts of the application.

Not sure if this has helped, but @angel, @lvalverde and myself are happy to talk about this anytime. Feel free to ask a question in #design on Slack

**Comment by Angelmmiguel** [comment]
Thank you very much for the detailed summary @earnubs. I think you didn't miss any point we've talked about. I'm gonna start working on it and ask you for the reviews!

**Comment by Angelmmiguel** [comment]
Done! I'll release v4.0.0 soon 🎉
